Add support for users
spacelift-io/terraform-provider-spacelift pull request #474
Opened 2023-10-10 09:33 UTC by mwasilew2

## Description of the change

> Description here

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (non-breaking change that adds documentation)

## Related issues

> Fix [#1]()

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
- [ ] All tests related to the changed code pass in development
- [ ] Examples for new resources and data sources have been added
- [ ] Default values have been documented in the description (e.g., "Dummy: (Boolean) Blah blah. Defaults to `false`.)
- [ ] If the action fails that checks the documentation: Run `go generate` to make sure the docs are up to date

### Code review

- [ ] This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] Pull Request is no longer marked as "draft"
- [ ] Reviewers have been assigned
- [ ] Changes have been reviewed by at least one other engineer

2023-10-10 13:15 UTC, mwasilew2 commented
This is blocked on API changes necessary on the backend side

2023-10-13 14:01 UTC, mwasilew2 commented
blocked by: https://github.com/spacelift-io/backend/pull/5658

2023-10-17 15:27 UTC, mwasilew2 commented
The backend PR was merged, the tests are passsing, this is ready for review

2023-10-19 09:11 UTC, michieldewilde requested changes
Only the naming is an issue.

2023-10-19 09:11 UTC, michieldewilde commented on spacelift/provider.go
> +				"spacelift_user_mapping":                 resourceUserMapping(),
it should be called `spacelift_user` this is the name we are using in the UI.

2023-10-19 09:11 UTC, michieldewilde commented on spacelift/resource_user_mapping_test.go
> +	t.Run("can remove one access", func(t *testing.T) {
incomplete test?

2023-10-19 09:12 UTC, mwasilew2 commented on spacelift/resource_user_mapping_test.go
> +	t.Run("can remove one access", func(t *testing.T) {
oopsie xD

2023-10-23 12:15 UTC, mwasilew2 commented
ping @michieldewilde

2023-10-23 12:18 UTC, michieldewilde approved these changes

2023-10-23 12:19 UTC, merged